language: go
os:
  - osx

branches:
  only:
    - master

go:
  - 1.15.x

env:
  global:
    - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint

before_script:
  - go vet ./...
  - go test -v ./...

script:
  - go build -ldflags "-s -w"
