language: go

go:
  - 1.16.x

addons:
  apt:
    packages:
      - upx
env:
  - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint

before_script:
  - go vet ./...
  - go test -v ./...

script:
  - go build
  - upx --brute jam

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: jam
  skip_cleanup: true
