language: go

go:
  - 1.16.x

addons:
  apt:
    packages:
      - upx
env:
  - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint

before_script:
  - go vet ./...
  - go test -v ./...

script:
  - go build

after_script:
  - upx --brute jam
